spring.application.name=CommentAnalysis
# ???????????
spring.devtools.remote.secret=analysis_reviews
# ????????
spring.devtools.remote.url= http://43.139.160.67/:8081

spring.web.resources.static-locations=file:/www/wwwroot/dachuang/user/resource/analysis_reviews

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB